# Generated by Django 5.2.8 on 2025-12-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='customer_segment',
            field=models.CharField(blank=True, choices=[('VIP', 'VIP'), ('LOYAL', 'Loyal'), ('ACTIVE', 'Active'), ('AT_RISK', 'At Risk'), ('NEW', 'New'), ('DORMANT', 'Dormant')], help_text='Cached ML customer segment', max_length=20, null=True),
        ),
    ]
