# Generated by Django 5.2.8 on 2025-12-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='last_price_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('dynamic', 'Dynamic'), ('cached', 'Cached'), ('override', 'Override')], default='manual', max_length=20),
        ),
    ]
