# Generated by Django 5.2.8 on 2025-12-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_base_price_product_current_price_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productreview',
            table='catalog_product_review',
        ),
    ]
