# Generated by Django 5.2.8 on 2025-12-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySalesCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('orders', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reports_monthlysalescache',
                'unique_together': {('year', 'month')},
            },
        ),
    ]
