# Generated by Django 5.2.8 on 2025-12-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon_allowed_payment_methods_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='allowed_payment_methods',
            field=models.JSONField(blank=True, default=list, help_text='Empty = allowed for all payment methods'),
        ),
    ]
