# Generated by Django 5.2.8 on 2025-12-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_coupon_allowed_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final product price at time of order (after dynamic pricing)', max_digits=10, null=True),
        ),
    ]
