# Generated by Django 5.2.8 on 2025-12-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_price_at_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnrequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='order',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='order_item',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount (e.g. 10.5 for 10.5%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal')], default='normal', max_length=30),
        ),
        migrations.DeleteModel(
            name='ReplacementRequest',
        ),
        migrations.DeleteModel(
            name='ReturnRequest',
        ),
    ]
