# Generated by Django 5.2.8 on 2025-12-13 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_enabled', models.BooleanField(default=True)),
                ('features', models.JSONField(default=dict)),
                ('last_cached', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ml_engine_automation_config',
            },
        ),
        migrations.CreateModel(
            name='AutomationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accuracy', models.FloatField(default=0.0)),
                ('weekly_impact', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'ml_engine_automation_module',
            },
        ),
        migrations.CreateModel(
            name='AutomationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('selected_model', models.CharField(default='prophet', max_length=64)),
            ],
            options={
                'db_table': 'ml_engine_automation_setting',
            },
        ),
        migrations.CreateModel(
            name='AutomationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime', models.FloatField(default=99.0)),
                ('hours_saved', models.IntegerField(default=0)),
                ('next_retrain_days', models.IntegerField(default=7)),
            ],
            options={
                'db_table': 'ml_engine_automation_stats',
            },
        ),
        migrations.CreateModel(
            name='ForecastCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='prophet', max_length=64)),
                ('horizon_months', models.IntegerField(default=3)),
                ('forecast_next_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('time_range', models.CharField(blank=True, max_length=64)),
                ('actual', models.JSONField(default=dict)),
                ('forecast', models.JSONField(default=dict)),
                ('model_metrics', models.JSONField(default=dict)),
                ('top_predictions', models.JSONField(default=list)),
                ('insights', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ml_engine_forecast_cache',
            },
        ),
        migrations.CreateModel(
            name='InventoryOptimizationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField(default=dict)),
                ('low_items', models.JSONField(default=list)),
                ('critical_items', models.JSONField(default=list)),
                ('insights', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ml_engine_inventory_optimization_cache',
            },
        ),
        migrations.CreateModel(
            name='MLCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ml_engine_cache',
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128, unique=True)),
                ('order_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'ml_engine_sales_record',
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField()),
                ('recommended_product', models.IntegerField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_engine_recommendation_log',
            },
        ),
    ]
