# Generated by Django 5.2.8 on 2025-11-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandPricePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('demand', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='priceadjustment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='priceadjustment',
            name='demand_score',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='priceadjustment',
            name='suggestion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
