# Generated by Django 5.2.8 on 2025-11-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_demandpricepoint_alter_priceadjustment_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemandPricePoint',
        ),
        migrations.AlterModelOptions(
            name='priceadjustment',
            options={},
        ),
        migrations.RemoveField(
            model_name='priceadjustment',
            name='demand_score',
        ),
        migrations.RemoveField(
            model_name='priceadjustment',
            name='suggestion',
        ),
    ]
