# Generated by Django 5.2.8 on 2025-12-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accuracy', models.FloatField(default=0.0)),
                ('weekly_impact', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True)),
                ('key', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uptime', models.FloatField(default=99.0)),
                ('hours_saved', models.IntegerField(default=0)),
                ('next_retrain_days', models.IntegerField(default=7)),
            ],
        ),
        migrations.DeleteModel(
            name='AutomationConfig',
        ),
    ]
