# Generated by Django 5.2.8 on 2025-12-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('selected_model', models.CharField(default='prophet', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'automation_setting',
            },
        ),
        migrations.CreateModel(
            name='ForecastCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='prophet', max_length=64)),
                ('horizon_months', models.IntegerField(default=3)),
                ('forecast_next_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0.0, max_digits=6)),
                ('time_range', models.CharField(blank=True, default='', max_length=64)),
                ('actual', models.JSONField(default=dict)),
                ('forecast', models.JSONField(default=dict)),
                ('model_metrics', models.JSONField(default=dict)),
                ('top_predictions', models.JSONField(default=list)),
                ('insights', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'forecast_cache',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128, unique=True)),
                ('order_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'sales_record',
                'ordering': ['-order_date'],
            },
        ),
    ]
